// <auto-generated />
using System;
using Mantenimiento.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mantenimiento.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MantenimientoDbContext))]
    [Migration("20260301012715_AddMasterModulesColumns")]
    partial class AddMasterModulesColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mantenimiento.Domain.Entities.Dependencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Regional")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dependencias");
                });

            modelBuilder.Entity("Mantenimiento.Domain.Entities.EncuestaSatisfaccion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Calificacion")
                        .HasColumnType("int");

                    b.Property<string>("Comentarios")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRespuesta")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrdenTrabajoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrdenTrabajoId")
                        .IsUnique();

                    b.ToTable("Encuestas");
                });

            modelBuilder.Entity("Mantenimiento.Domain.Entities.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockActual")
                        .HasColumnType("int");

                    b.Property<string>("TipoMaterial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Materiales");
                });

            modelBuilder.Entity("Mantenimiento.Domain.Entities.Operacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRealizacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("HorasHombre")
                        .HasColumnType("int");

                    b.Property<Guid>("OrdenTrabajoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrdenTrabajoId");

                    b.ToTable("Operaciones");
                });

            modelBuilder.Entity("Mantenimiento.Domain.Entities.OrdenTrabajo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DependenciaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFinalizacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("SolicitanteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TecnicoAsignadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Urgencia")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DependenciaId");

                    b.HasIndex("SolicitanteId");

                    b.HasIndex("TecnicoAsignadoId");

                    b.ToTable("OrdenesTrabajo");
                });

            modelBuilder.Entity("Mantenimiento.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DependenciaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DependenciaId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("MaterialOperacion", b =>
                {
                    b.Property<Guid>("MaterialesUsadosId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OperacionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MaterialesUsadosId", "OperacionId");

                    b.HasIndex("OperacionId");

                    b.ToTable("MaterialOperacion");
                });

            modelBuilder.Entity("Mantenimiento.Domain.Entities.EncuestaSatisfaccion", b =>
                {
                    b.HasOne("Mantenimiento.Domain.Entities.OrdenTrabajo", "OrdenTrabajo")
                        .WithOne("Encuesta")
                        .HasForeignKey("Mantenimiento.Domain.Entities.EncuestaSatisfaccion", "OrdenTrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenTrabajo");
                });

            modelBuilder.Entity("Mantenimiento.Domain.Entities.Operacion", b =>
                {
                    b.HasOne("Mantenimiento.Domain.Entities.OrdenTrabajo", "OrdenTrabajo")
                        .WithMany("Operaciones")
                        .HasForeignKey("OrdenTrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenTrabajo");
                });

            modelBuilder.Entity("Mantenimiento.Domain.Entities.OrdenTrabajo", b =>
                {
                    b.HasOne("Mantenimiento.Domain.Entities.Dependencia", "Dependencia")
                        .WithMany()
                        .HasForeignKey("DependenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mantenimiento.Domain.Entities.Usuario", "Solicitante")
                        .WithMany()
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mantenimiento.Domain.Entities.Usuario", "TecnicoAsignado")
                        .WithMany()
                        .HasForeignKey("TecnicoAsignadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Dependencia");

                    b.Navigation("Solicitante");

                    b.Navigation("TecnicoAsignado");
                });

            modelBuilder.Entity("Mantenimiento.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Mantenimiento.Domain.Entities.Dependencia", "Dependencia")
                        .WithMany("Personal")
                        .HasForeignKey("DependenciaId");

                    b.Navigation("Dependencia");
                });

            modelBuilder.Entity("MaterialOperacion", b =>
                {
                    b.HasOne("Mantenimiento.Domain.Entities.Material", null)
                        .WithMany()
                        .HasForeignKey("MaterialesUsadosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mantenimiento.Domain.Entities.Operacion", null)
                        .WithMany()
                        .HasForeignKey("OperacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mantenimiento.Domain.Entities.Dependencia", b =>
                {
                    b.Navigation("Personal");
                });

            modelBuilder.Entity("Mantenimiento.Domain.Entities.OrdenTrabajo", b =>
                {
                    b.Navigation("Encuesta");

                    b.Navigation("Operaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
